### ISSUE TITLE
testCases not running on new ns3lxc installation

### ISSUE THREAD

**Issue by natzlob** [buzz66boy/NS-3_LXC#42]
I have gone meticulously through the ns3-lxc installation instructions at https://github.com/buzz66boy/ns3-lxc/wiki/Install-&-Run-ns3-lxc and successfully installed all the dependencies for ns3-lxc as well as ns3-lxc-0.1 without a problem. I am using yaml-cpp-0.6.0 and apparently builds fine, have set my environment for c++11, and ns3 runs just fine. However, none of the test cases are running successfully. I have checked online YAML validators and the syntax is valid. However, running any of the test cases with bin/ns3lxc resources/test_cases/testCase2.yaml throws the following error: terminate called after throwing an instance of 'YAML::BadFile'
  what():  yaml-cpp: error at line 0, column 0: bad file
Aborted (core dumped)

Please NOTE: I am running from the ns3-lxc directory where bin/ns3lxc exists and the test cases are in the directory stated in the command.

I am running on an Ubuntu 16.04 system.

Please assist!

**Comment by buzz66boy** [comment]
Apologies for the late reply; I've been away from the project for a while. I have been unable to replicate the issue using the latest libyaml provided via ubuntu repositories (version: 0.5.2-4ubuntu1).
I am able to run test case 2 successfully. 
Did you install via the "sudo apt install libyaml-cpp-dev" command?

**Comment by natzlob** [comment]
Hi, I still have this issue, actually. Have recently come back to it. Yes, libyaml-cpp-dev is installed fine
